FORMAT: 1A
HOST: http://retail.oracle.org/

# Order API

Allows developers to query for order information. Developers can decide if they want 
to receive all the details for the particular order or just the summary. 

## Orders [/orders]

### Get All Orders [GET]
Returns all orders information

+ Response 200 (application/json)

        [
            {
                "orderid": "1000",
                "po_date": "Aug 6, 2016 5:58:28 PM",
                "order_status": "PENDING"
            },
            {
                "orderid": "2000",
                "po_date": "July 12, 2016 4:58:28 PM",
                "order_status": "SHIPPED"
            },
            {
                "orderid": "3000",
                "po_date": "Feb 8, 2016 3:58:28 PM",
                "order_status": "DELIVERED"
            }
        ]

## Order Details [/orders/details/{item}]

### Get order details [GET]
Returns all details for a specific order

+ Parameters
    + item (number) - Order item number.

+ Response 200 (application/json)

        [
            {
                "OrderName": "Patrick Shepherd",
                "orderid": "1000",
                "reference_no": "20",
                "remarks": "200",
                "po_date": "Aug 6, 2016 5:58:28 PM",
                "order_type": "PENDING",
                "itemList": [
                    {
                        "gl_dimension_pkids": "1001,1002",
                        "gl_dimension_code": "XYZ,ABC",
                        "gl_code_reference": "Samsung 27 inches Widescreen LED Monitor, Black",
                        "gl_code": "XYZ",
                        "item": "1000",
                        "item_type": "INV",
                        "qty": "10",
                        "unit_price": "$189.99"
                    },
                    {
                        "gl_dimension_pkids": "1001,1002",
                        "gl_dimension_code": "XYZ,ABC",
                        "gl_code_reference": "HP LaserJet Pro M402dn Monochrome Laser Printer",
                        "gl_code": "XYZ",
                        "item": "2000",
                        "item_type": "INV",
                        "qty": "5",
                        "unit_price": "$199.99"
                    }]
            }
        ]


## Order Summary [/orders/summary/{item}]

### Get order Summary [GET]
Returns only a summary of the order (name, PO date, order status and order total).

+ Parameters
    + item (number) - Order item number.

+ Response 200 (application/json)

        [
            {
                "orderid": "1000",
                "OrderName": "Patrick Shepherd",                
                "po_date": "Aug 6, 2016 5:58:28 PM",
                "order_status": "PENDING",
                "order_total": "$2,890.94"
            }
        ]